<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="cuid.net" Version="7.0.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="SharpCompress" Version="0.50.3" />
        <PackageReference Include="Tomlyn" Version="2.10.1" />
        <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    </ItemGroup>

</Project>
